EXTRA_CMDLINE: /init
rancher:
  defaults:
    hostname: hub
    network:
      dns:
        nameservers:
        - 10.0.8.2
        - 10.0.1.1
  docker:
    insecure_registry:
    - 10.0.0.0/8
    - 192.168.0.0/16
    registry_mirror: https://3c51jta7.mirror.aliyuncs.com
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - 10.0.8.2
    nameservers:
    - 10.0.8.2
  services_include:
    open-vm-tools: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgV9ZF7exUyBXFnAMiMI0ei05CE8h00HykLU7OxquBFQ6hig0sl6/SxfFm2tJdMjJwHbSkWYZXiW+WpYCpMluxGdU65uz0nxQAXmCRiBf7kpeYKREqHn/nykahF8HDA0eMjOLtQI+EPBIO5p4/of2s+m4vcUjHedPw+Z3R0ni++apYTpMr42pKL6PFtRTIIZ60atFiWU/7S55JTx03C935HA242h7pSN4UExZmNxq4LFN0xW8hDIWLj7EEbt7wCGHJqPYA1ornp0qEBTj8XRBZCR+05y9ZKvpIrHti+QDVFakkKqDEto6ZhmA8IAv8gLuFDIRuFd2xQiKgkxttKsHz
  rancher@rancher
